import 'package:get/get.dart';

class LocalString extends Translations{
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'en_US ':{
      'Bienvenue sur notre application\nde pressing!':'Welcome to our laundry application!',
      'Nous vous aidons à gérer tous vos besoins de pressing.':'We help you manage all your dry cleaning needs.',
      'Profitez de nos services de qualité':'Take advantage of our quality services',
      'Avec nous, vous pouvez compter sur un service rapide et fiable.':'With us you can count on fast and reliable service.',
      'Commencez dès maintenant':'Get started now',
      'Téléchargez notre application et lancez votre première commande.':'Download our app and place your first order.',
      "L'email ou le mot de passe n'existe pas ! Veuillez réessayer":'The email or password does not exist! Try Again',
      'Connectez-vous':'Log in',
      'Email ou Numéro de téléphone':'Email or Phone Number',
      'Veuillez entrer votre email ou numéro de téléphone':'Please enter your email or phone number',
      'Mot de passe':'Password',
      'Veuillez entrer votre mot de passe':'Please enter your password',
      'Se connecter':'Log in',
      'Mot de passe oublié?':'Forgot your password?',
      'Vous n\'avez pas de compte ? Inscrivez-vous':'You do not have an account ? Register',
      'Créer un compte':'Create an account',
      'Nom':'Name',
      'Adresse e-mail':'E-mail address',
      'Numéro de téléphone':'Phone number',
      //"Prix :".tr + 
      'Mot de passe':'Password',
      "S\'inscrire":'Register',
      'Vous avez déjà un compte ? Se connecter':'Already have an account ? To log in',
      'Accueil':'Home',
      'Historique':'History',
      'Profil':'Profil',
      'Choisissez un type de quantification':'Choose a quantization type',
      'Lavage par\nquantité':'Wash by\nquantity',
      'Lavage par kilogramme':'Wash per kilogram',
      'Details de la commande':'Details of the order',
      'Valider La Commande et Payer':'Validate the Order and Pay',
      'Valider La Commande':'Validate the order',
      'Prix :':'Price : ',
      'RÉCEPTION  ':'RECEPTION',
      'Type de livraison :  ':'Type of delivery:',
      'Quartier :  ':'Neighborhood :',
      'Date de Réception :  ':'Date of receipt :',
      'Heure de Réception :  ':'Reception time:',
      'LIVRAISON  ':'DELIVERY',
      'Quartier de livraison :  ':'Delivery district:',
      'Date de livraison :  ':'Delivery date :',
      'Heure de livraison :  ':'Delivery time :',
      'Quantité : ':'Quantity :',
      'LES ARTICLES':'THE ARTICLES',
      'Noms':'Names',
      'Quantité':'Quantity',
      "Erreur de chargement. Veuillez relancer l'application":'Loading error. Please restart the application',
      'INFOMATIONS SUPPLÉMENTAIRE':'ADDITIONAL INFORMATION',
      'Type de Service : ':'Type of Service:',
      'Type Livraison : ':'Delivery Type:',
      'Type Lavage : ':'Wash Type:',
      'Date de Collecte : ':'Collection Date:',
      'Heure de Collecte : ':'Collection Time:',
      'Lieu de Collecte : ':'Collection Location:',
      'Date de Livraison : ':'Delivery date :',
      'Heure de Livraison : ':'Delivery time :',
      'Lieu de Livraison : ':'Place of delivery :',
      'T-Shirt Blanc':'White Tshirt',
      'Chemise':'Shirt',
      'Chemise Blanc':'White shirt',
      'Blouse Médicale':'Medical Coat',
      'Pull Over Blanc':'White Sweater',
      'Pull Over':'Sweater',
      'Pantalon Simple':'Simple Pants',
      'Tenu en Cuir':'Leather Outfit',
      'Pantalon Blanc':'White pants',
      'Jean Habit':'jean outfit',
      'Jupe':'Skirt',
      'Jupe Blanc':'Skirt White',
      'Robe':'Dress',
      'Tenu Tradi':'Traditionnal dress',
      'Drap':'Sheets',
      'Rideaux':'Curtains',
      'Serviette':'Towel',
      'Couette':'Comforter',
      'Nappe':'Tablecloth',
      'Tapis':'Tablecloth',
      'Oreiller':'Pillow',
      'Chaussure Sport':'Sports Shoe',
      'Ballerine':'Ballerina',
      'Escarpin':'Pump',
      'Mocassin':'Moccasin',
      'Sandale':'Sandal',
      'Bottes':'Boots',
      'Mode Paiement :   En Ligne':'Payment method: Online',
      'Mode de Paiement : A la collecte des linges':'Method of Payment: Upon collection of linen',
      "Vous n'avez pas de commande":"You don't have an order",
      'Payé':'Paid',
      'Détails':'Details',
      'App Laverie':'App Lavery',
      'Nos services':'Our services',
      'Lavage et repassage':'Washing and ironing',
      'Repassage':'Ironing',
      'Teinture':'Dyeing',
      'Lavage et teinture':'Washing and dyeing',
      'Lavage chaussure':'Shoe wash',
      'Reparation et Lavage':'Repair and Wash',
      'Comment sa marche ?':'How does it work ?',
      'Passer commande':'Place order',
      'Nous collectons \n à domicile':'We collect from home',
      'Nous prenons soin':'We take care',
      'Nous Livrons':'We deliver',
      'Temoignages':'Testimonials',
      'Cette application a révolutionné ma \n routine de lessive ! En quelques clics, \n je programme la collecte et la livraison \n de mon linge. ':'This app has revolutionized my laundry routine!\nIn just a few clicks, I schedule the collection\nand delivery of my laundry.',
      'Une application indispensable pour tous \n ceux qui manquent de temps pour faire leur \n lessive. La possibilité de choisir des options \n de lavage spécifiques est un plus.':'An essential app for anyone who lacks time\nto do their laundry. The ability to choose\n specific wash options is a plus.',
      'Je recommande vivement cette \n application à tous ceux qui \n cherchent une solution de laverie \n fiable et sans tracas ':'I highly recommend this app to anyone \nlooking for a reliable, hassle-free\nlaundry solution',
      'Porter plainte/Urgence':'File a complaint/Emergency',
      'Appel':'Call',
      'Ajouter vos tenues':'Add your outfits',
      'Continuer':'Continue',
      'Prix au Kilogramme (900 F)':'Price per Kilogram (900 F)',
      'Kilogramme':'Kilogram',
      'Prix':'Price',
      'A partir de 5 Kg':'From 5 Kg',
      'Vêtements Hauts':'Clothing Tops',
      'Vêtements Bas':'Clothing Bottoms',
      'Complets':'Complete',
      'Articles Maisons':'Articles Houses',
      'Choisissez la chaussure à laver':'Choose the shoe to wash',
      'Editer profil':'Edit profile',
      'Confidentialité':'Confidentiality',
      'Deconnexion':'Log ou',
      'Informations de livraison':'delivery information',
      'Type de livraison':'Delivery type',
      'Paiement à la Collecte des linges':'Payment upon collection of linens',
      'Paiement en ligne':'Online Payment',
      'Veuillez entrer votre quartier actuel ':'Please enter your current neighborhood',
      'Choisissez vos Linges':'Choose your linens',
      'Veuillez patienter Quelques Secondes.\nLa page de Paiement arrive.':'Please wait a few seconds.\nThe Payment page arrives.',
    },
    'fr_FR':{
      '':"Faites livrer plus facilement vos produits d'occasion",
      'sec1Btn': 'Commencer',
      'sec2Title':'Securité et économie',
      'sec2subTitle':'Chez Coli Express, nous garantissons du mieux possible, votre sécurité et celui de vos Colis.\nLe service mis en place dans notre struture, vous permet\nde moins dépenser votre argent pour faire transférer vos produit ',
      'sec3Title1':'Respect des gestes barrières',
      'sec3Title2':'Réception des produits à laéroport',
      'sec3Title3':'Livraison sécurisée et à temps',
      'appBarTxt1':'Nos valeurs',
      'appBarTxt2':'Notre histoire',
      'appBarTxt3':'Nos engagements',
      'appBarTxt4':'Rechercher',
      'appBarTxt5':'Publier trajets',

      'nosValeursTitle1':'Objectifs',
      'nosValeursSubTitle1':'Notre Objectif est de créer de la valeur pour tous nos clients.\nAfin d’y parvenir, nous devons savoir nous mettre à\nleur place et avoir une profonde empathie pour\nleurs besoins et contraintes.\nNous sommes donc utilisateurs de notre service,\nmembres de notre communauté.',
      'nosValeursTitle2':'Innovations',
      'nosValeursSubTitle2':'Nous innovons, nous prenons des risques, nous créons une solution de\nmobilité entièrement nouvelle, nous marchons hors des sentiers battus.\nDe temps en temps, nous échouons sur le chemin. Cela fait partie de l’expérience.\nMais nous apprenons de nos erreurs et devenons meilleurs en conséquence.',
      'nosValeursTitle3':'Réalisations',
      'nosValeursSubTitle3':'Nous comptons aujourdhui plus de 1000 clients satisfais de nos prestations\nen seulement 7 mois',

      'foottxt1':'Politiques de confidentialité',
      'foottxt3':'Centre daide',
      'foottxt2 ':'Qui sommes nous'

    }
  };
}